name: Caddy Validate Action
description: 'Validate Caddyfile using a Caddy container image'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  Caddyfile:
    description: 'Path to the Caddyfile to validate'
    required: false
    default: 'Caddyfile'
  Caddy-container-image:
    description: 'Caddy Docker image to use for validation'
    required: false
    default: 'caddy:latest'

  
runs:
  using: 'composite'
  steps:
    - name: Copy validation script to working directory
      run: cp "${{ github.action_path }}/parse-validate.pl" .
      shell: bash

    - name: Run validate container and parse output
      run: |
          docker run --rm \
            --entrypoint caddy \
            -v ./"$CADDYFILE:/etc/caddy/Caddyfile" \
            $CADDY_CONTAINER_IMAGE \
            validate --config /etc/caddy/Caddyfile 2>&1 | perl ./parse-validate.pl
      shell: bash
      env:
        CADDYFILE: ${{ inputs.Caddyfile }}
        CADDY_CONTAINER_IMAGE: ${{ inputs.Caddy-container-image }}
